### ISSUE TITLE
这咋运行

### ISSUE THREAD

**Issue by saysea** [Zoctan/Wechat-MiniJob#1]
允许不起来

**Comment by Zoctan** [comment]
只有小程序端

**Comment by saysea** [comment]
难受 为什么项目都只有前面的 没有后面的&nbsp; &nbsp;哥你知道为什么吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zoctan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 下午5:29
收件人:&nbsp;"Zoctan/Wechat-MiniJob"<Wechat-MiniJob@noreply.github.com&gt;;
抄送:&nbsp;"荘友"<1056735216@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zoctan/Wechat-MiniJob] 这咋运行 (#1)





 
只有小程序端

**Comment by Zoctan** [comment]
没有为什么，我只写了前端，没写后端
